export const VEGETABLE_LIST = "VEGETABLE_LIST"
export const VEGETABLE_REQUEST = "VEGETABLE_REQUEST"
export const VEGETABLE_ERROR = "VEGETABLE_ERROR"

export const PLACEORDER_DONE = "PLACEORDER_DONE"
export const PLACEORDER_REQUEST = "PLACEORDER_DONE"
export const PLACEORDER_ERROR = "PLACEORDER_DONE"

export const HISTORY_LIST = "HISTORY_LIST"
export const HISTORY_REQUEST = "HISTORY_REQUEST"
export const HISTORY_ERROR = "HISTORY_ERROR"